import Head from 'next/head'


export default function BlogIndex() {
  return (
    <div className= "container" >
      <Head>
        <title>Blog index-</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Blog Index</h1>
    <p>This is the Blog page</p>
    </div>
  )
}
