import Head from 'next/head'
import axios from 'axios';
import { useState, useEffect } from 'react';

import styles from '../styles/Home.module.css'

export default function About({data}) {
    const [state, setState]= useState({
        name: data.name
    })
    // useEffect(()=>{
    //     console.log('Component Loaded')
    //     axios.get("https://pokeapi.co/api/v2/pokemon/pikachu")
    //     .then((response)=>{
    //         console.log(response.data.name)
    //         setState({
    //             name: response.data.name
    //         })
    //     })
    // }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon-</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Pokemon</h1>
    <h2>{state.name}</h2>
    <p>This is the Pokemon page</p>
    </div>
  );
}

// //Static site Generation
// export async function getStaticProps() {
//     //call an external API endpoint to get posts.
//     //You can use any data fetching library
//     const res = await fetch ("https://pokeapi.co/api/v2/pokemon/pikachu");
//     const data = await res.json();


//     //By returning {props: data}, the Blog component
//     //will receive 'data' as a prop at build time
//     return{
//         props:{
//             data,
//         },
//     };
//   }

// Server Side
//this gets called on every request
export async function getServerSideProps(){
  //fetch data from external API
  const res = await fetch("https://pokeapi.co/api/v2/pokemon/pikachu")
  const data = await res.json()

  //Pass data to the page via props
  return{props:{data}}
}