import Head from 'next/head'
import axios from 'axios';
import { useState, useEffect } from 'react';

import styles from '../styles/Home.module.css'

export default function About() {
    const [state, setState]= useState({
        name: 'No-name'
    })
    useEffect(()=>{
        console.log('Component Loaded')
        axios.get("https://pokeapi.co/api/v2/pokemon/pikachu")
        .then((response)=>{
            console.log(response.data.name)
            setState({
                name: response.data.name
            })
        })
    }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon-</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Pokemon</h1>
    <h2>{state.name}</h2>
    <p>This is the Pokemon page</p>
    </div>
  )
}
